---
title: "DSA_stroma_Ly6a+_NOX"
output: html_notebook
---


```{r}
library(SingleCellExperiment)
library(Seurat)
library(muscat)
library(ggplot2)
library(dplyr)
library(fgsea)
```


```{r}
seuratNOX <- readRDS("C:/Users/.../stroma_NOX.rds")
```


# Differential state analysis
```{r}
seurat.tmp <- seuratNOX
seurat.tmp$UniqueSample <- paste(seurat.tmp$orig.ident)
# Technically P3_P7_1_Bar1 and P3_P7_2_Bar1, for example, are the same mice--should merge
seurat.tmp$UniqueSample[seurat.tmp$UniqueSample %in% c("P3_P7_1", "P3_P7_2")] <- "P3_P7"
seurat.tmp$UniqueSample <- paste(seurat.tmp$UniqueSample, seurat.tmp$Barcode, sep="_")

DefaultAssay(seurat.tmp) <- "RNA" #can switch back to integrated if desired

seurat.sce <- as.SingleCellExperiment(seurat.tmp)

seurat.sce <- prepSCE(seurat.sce,
                      kid = "Groups",
                      gid = "Age",
                      sid = "UniqueSample",
                      drop=T)
seurat.sce$group_id <- factor(seurat.sce$group_id, levels=c("P3", "P7", "P14"))


pb <- aggregateData(seurat.sce,
                    assay = "counts", fun = "sum",
                    by = c("cluster_id", "sample_id"))

pb$group_id <- factor(pb$group_id, levels=c("P3", "P7", "P14"))
res <- pbDS(pb, verbose = FALSE)
tmp <- seurat.sce
counts(tmp) <- as.matrix(counts(tmp))
result_table <- resDS(tmp, res, bind = "row", frq = FALSE, cpm = FALSE)
rm(tmp)

#Trim columns we don't really care about
result_table$p_adj.glb <- NULL

#Get the frequency of P3/HyP14 cells in a cluster that express a gene
count_mat <- as.matrix(seuratNOX[["RNA"]]@data) > 0
cluster_list <- unique(result_table$cluster_id)
result_table$P3.frq <- 0
P3_cells <- colnames(seuratNOX)[seuratNOX$Age == "P3"]
for(i in 1:length(cluster_list)){
  #Which cells to calc freq on
  cluster_cells <- colnames(seuratNOX)[seuratNOX$Groups == cluster_list[i]]
  test_cells <- intersect(P3_cells, cluster_cells)
  #Which rows of result_table to fill
  row_ind <- which(result_table$cluster_id == cluster_list[i])
  frq <- rowSums(count_mat[result_table$gene[row_ind],test_cells]) / length(test_cells)
  result_table$P3.frq[row_ind] <- frq
}


P7_cells <- colnames(seuratNOX)[seuratNOX$Age == "P7"]
result_table$P7.frq <- 0
for(i in 1:length(cluster_list)){
  #Which cells to calc freq on
  cluster_cells <- colnames(seuratNOX)[seuratNOX$Groups == cluster_list[i]]
  test_cells <- intersect(P7_cells, cluster_cells)
  #Which rows of result_table to fill
  row_ind <- which(result_table$cluster_id == cluster_list[i])
  frq <- rowSums(count_mat[result_table$gene[row_ind],test_cells]) / length(test_cells)
  result_table$P7.frq[row_ind] <- frq
}

P14_cells <- colnames(seuratNOX)[seuratNOX$Age == "P14"]
result_table$P14.frq <- 0
for(i in 1:length(cluster_list)){
  #Which cells to calc freq on
  cluster_cells <- colnames(seuratNOX)[seuratNOX$Groups == cluster_list[i]]
  test_cells <- intersect(P14_cells, cluster_cells)
  #Which rows of result_table to fill
  row_ind <- which(result_table$cluster_id == cluster_list[i])
  frq <- rowSums(count_mat[result_table$gene[row_ind],test_cells]) / length(test_cells)
  result_table$P14.frq[row_ind] <- frq
}


write.csv(result_table, file = "C:/Users/.../DSA_stroma_Ly6a+_NOX.csv", row.names = F)
```


# GSEA on all CellTypes by logFC
```{r}
hallmarks <- fgsea::gmtPathways("C:/Users/.../GeneLists/h.all.v7.2.symbols.gmt")
kegg <- fgsea::gmtPathways("C:/Users/.../GeneLists/c2.cp.kegg.v7.2.symbols.gmt")
go <- fgsea::gmtPathways("C:/Users/.../GeneLists/c5.go.v7.2.symbols.gmt")
reactome <- fgsea::gmtPathways("C:/Users/.../GeneLists/c2.cp.reactome.v7.2.symbols.gmt")

gene_sets <- c(hallmarks, kegg, go, reactome)
```

```{r}
runGSEA <- function(cluster){
  results <- filter(result_table, cluster_id == cluster)
  results <- filter(results, P3.frq >= 0.05 |
                      P14.frq >= 0.05)
  results <- arrange(results, desc(logFC))
  
  cluster_genes <- results$logFC
  names(cluster_genes) <- toupper(results$gene)
  
  gsea <- fgsea(pathways = gene_sets,
                stats = cluster_genes,
                minSize=15,
                maxSize=500)
  gsea$cluster <- cluster
  
  return(gsea)
}
```
```{r}
cluster_list
```

```{r}
cluster_list <- unique(result_table$cluster_id)

fgsea_results <- lapply(cluster_list, runGSEA)
```
```{r}
fgsea_results <- do.call("rbind", fgsea_results)
fgsea_results <- as.data.frame(fgsea_results)
fgsea_results$leadingEdge <- as.character(fgsea_results$leadingEdge)
```
```{r}
writexl::write_xlsx(fgsea_results, path = "C:/Users/.../dGSEA_stroma_Ly6a+_NOX.xlsx")
```
  









